# Generated by Django 6.0.2 on 2026-02-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
