# Generated by Django 6.0.2 on 2026-03-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='trailer_url',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
