# Generated by Django 6.0.2 on 2026-06-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
