# Generated by Django 6.0.2 on 2026-06-30 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reserved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
