# Generated by Django 6.0.2 on 2026-06-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_booking_reserved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
